# Generated by Django 4.2.17 on 2025-02-13 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Обратная связь покупателя', 'verbose_name_plural': 'Обратная связь покупателей'},
        ),
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='images/user.png', upload_to='avatars/', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_phone_verified',
            field=models.BooleanField(default=False, verbose_name='Телефон подтвержден'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_seller',
            field=models.BooleanField(default=False, verbose_name='Продавец'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='Номер телефона'),
        ),
    ]
