# Generated by Django 4.2.18 on 2025-01-28 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='lang',
            field=models.CharField(blank=True, default='ru', max_length=5, null=True),
        ),
    ]
