# Generated by Django 4.2.18 on 2025-01-28 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_item_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tags_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.taggeditem'),
        ),
    ]
