# Generated by Django 4.2.18 on 2025-01-28 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_item_tags_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='tags_2',
        ),
    ]
