# Generated by Django 4.2.17 on 2025-01-28 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_item_tags_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='lang',
        ),
    ]
