# Generated by Django 4.2.17 on 2025-02-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_seller_options_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Одобрено администратором'),
        ),
    ]
