# Generated by Django 4.2.17 on 2025-02-02 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='address_line_1',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='address_line_2',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='email',
        ),
    ]
